availability_pattern: "Jeremy office hours"
min_notice_hours: 12
max_advance_days: 90
default_timezone: "America/New_York"
theme_color: "#CCE2D8"
apps_script_url: "https://script.google.com/macros/s/AKfycbxcBySOIJq1f2SP7oVTr3JgBc91qTxdFaQKknnoe8VdLJDxijKV-gGdFb9mNHdJLMMN/exec"
